# Butterfly 主题配置文件
# 文档: https://butterfly.js.org/posts/4aa8abbe/

# 主题颜色配置
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"

# 主页配置
index_img: /img/hero-bg.svg
index_site_info_top: 50%  # 将标题下移到页面中心

# 导航栏设置
nav:
  logo: /img/logo.svg
  display_title: true
  display_post_title: true
  fixed: false

# 导航菜单配置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  项目: /projects/ || fas fa-code
  团队: /teams/ || fas fa-users
  资源库||fas fa-book:
    保研: /graduate/ || fas fa-graduation-cap
    就业: /career/ || fas fa-briefcase
  加入我们||fas fa-handshake:
    招新: /jobs/ || fas fa-user-plus
    关于: /about/ || fas fa-heart
    联系: /contact/ || fas fa-envelope

# 代码高亮
highlight_theme: mac
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_height_limit: 200

# 社交图标
social:
  fab fa-github: https://github.com/PaxonHuang/LapinEX || Github
  fas fa-envelope: mailto:contact@lapinex.com || Email

# 头像
avatar:
  img: /img/logo.svg
  effect: true # 保持旋转效果

# 顶部图
top_img: /img/hero-bg.svg # 全站默认封面

# 文章封面
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:
    - /img/hero-bg.svg # 统一使用此封面

# 侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description: 大学计算机社团
    button:
      enable: true
      icon: fab fa-github
      text: 关注我们
      link: https://github.com/PaxonHuang/LapinEX
  card_announcement:
    enable: true
    content: 欢迎加入我们的计算机社团！
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order: 
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order: 
  card_tags:
    enable: true
    limit: 40
    color: false
    sort_order: 
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order: 
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: 

# 页脚设置
footer:
  owner:
    enable: true
    since: 2023
  custom_text: <a href="https://github.com/PaxonHuang/LapinEX">LapinEX</a> - 大学计算机社团
  copyright: true

# 搜索系统
local_search:
  enable: true
  preload: true
  CDN:

# 页面元数据
post_meta:
  page:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true
  post:
    date_type: both
    date_format: relative
    categories: true
    tags: true
    label: true

# 文章版权
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 相关文章推荐
related_post:
  enable: true
  limit: 6
  date_type: created

# 目录
toc:
  enable: true
  number: true
  auto_open: true

# 分享功能
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# 评论系统
# 可以根据需要选择评论系统
comments:
  use: Disqus
  text: true
  lazyload: false
  count: true
  card_post_count: false

# 站点统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 页面加载动画
preloader: true

# 字体设置
font:
  global-font-size: 16px
  code-font-size: 14px
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft YaHei", monospace

# CDN 设置
# 可以使用默认 CDN 或自定义
CDN:
  internal_provider: local
  third_party_provider: cdnjs
  version: false